//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMIForAll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicador_Dato
    {
        public int Id { get; set; }
        public string Valor { get; set; }
        public string Fecha { get; set; }
        public int IndicadorId { get; set; }
    
        public virtual Indicador Indicador { get; set; }
    }
}
