//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMIForAll.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objetivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Objetivo()
        {
            this.Indicadores = new HashSet<Indicador>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Metrica { get; set; }
        public string Ponderacion { get; set; }
        public int CMIId { get; set; }
        public int PerspectivaId { get; set; }
    
        public virtual CMI CMI { get; set; }
        public virtual Perspectiva Perspectiva { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicador> Indicadores { get; set; }
    }
}
